Fluveny/fluveny-api

- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/GrammarRuleEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/LevelEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/ModuleEntity.java
This branch adds the module, grammar rule and level entities for further tasks development.
> Creating the entities for a module, grammar rule and level 

- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/GrammarRuleEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/LevelEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/ModuleEntity.java
In this branch I added the ID notation that was missing in the antities.
> Adding ID notation to identities

- src/main/java/com/fluveny/fluveny_backend/api/dto/ModuleRequestDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/ModuleResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
- src/main/java/com/fluveny/fluveny_backend/exception/GlobalExceptionHadler.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/repository/ModuleRepository.java
In this branch, classes for the module's repository, service, and both request and response DTOs were created, along with exception handling for invalid fields.
> Creating repository, service, and DTO classes, along with invalid field exception handling

- src/main/java/com/fluveny/fluveny_backend/api/controller/IntroductionController.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/IntroductionDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/IntroductionMapper.java
- src/main/java/com/fluveny/fluveny_backend/business/service/IntroductionService.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/IntroductionEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/TextBlockEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/repository/IntroductionRepository.java
Adding the files:
-Introduction DTO
-Introduction Service
-Introduction Controller
-Introduction Mapper
-Introduction Entity
-Introduction Repository
-Textblock Entity
> Services implementations of Introduction and text block

- src/main/java/com/fluveny/fluveny_backend/business/service/GrammarRuleService.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/repository/GrammarRuleRepository.java
US-2055  - grammar rule service and repository created
> feat: creating grammar rule service and repository - US-2055

- pom.xml
- src/main/java/com/fluveny/fluveny_backend/api/controller/IntroductionController.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/TextBlockEntity.java
- src/main/resources/application-dev.properties
- src/main/resources/application-test.properties
In this branch we fixed the pom.xml with the dependencies for sweggar and security.
> Fixing security, swagger and endpoint issues

- src/main/java/com/fluveny/fluveny_backend/RunOnStatup.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/ModuleController.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/ModuleMapper.java
In this branch, the model controller with a creation endpoint was added, in addition to the mapper. A class was also added to initialize the database with 2 items so that it would be possible to test the creation of the module.
> Adding controller and mapper to module

- src/main/java/com/fluveny/fluveny_backend/RunOnStatup.java
- src/main/java/com/fluveny/fluveny_backend/config/web/WebConfig.java
In this branch, I added the class for configuring CORS and fixed the problem with run, which was adding a new grammar rule and level every run.
>  Adding class for CORS configuration

- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
Making the repository grab by id not by title.
> Fixin problem in get module in service

- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleController.java
on this pull request, a swagger documentation for grammar rule controller was added.
> docs - adding swagger documentation to grammar rule controller US-2055

- src/test/java/com/fluveny/fluveny_backend/business/service/ModuleServiceTest.java
In this branch, the test class for the module edit service was added.
> Adding test class for service with the edit method

- src/main/java/com/fluveny/fluveny_backend/api/controller/IntroductionController.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/IntroductionDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/IntroductionMapper.java
Adding some swagger's annotations and fixing some problems with mapper.
> Adding some points in US-2080

- src/main/java/com/fluveny/fluveny_backend/api/controller/IntroductionController.java
- src/main/java/com/fluveny/fluveny_backend/business/service/IntroductionService.java
on this request, was added the update endpoint of module introduction from US-2555
> feat: adding endpoint to update module introduction

- src/main/java/com/fluveny/fluveny_backend/api/controller/ModuleController.java
- src/main/java/com/fluveny/fluveny_backend/exception/GlobalExceptionHandler.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/ModuleControllerTest.java
In this branch, a test class was created for the module controller, testing the responses of the POST and PUT endpoint. Some issues with the API responses and the exception class name were also fixed.
> creating test class for module controller POST and PUT endpoint

- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseController.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/ExerciseRequestDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/ExerciseResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/ModuleRequestDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/ExerciseMapper.java
- src/main/java/com/fluveny/fluveny_backend/api/response/exercise/ExerciseResponse.java
In this Pull Request, i'm trying to merge some features developed, like:
-GrammarRuleExerciseController
-ExerciseRequestDTO
-And others
I just modified one comment about que number of characters in ModuleRequestDTO
> Pull request about some tasks of User Story 2160

- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleController.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/LevelController.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/ModuleController.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/ModuleMapper.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ContentManagerService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ExerciseService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/GrammarRuleModuleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/GrammarRuleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/IntroductionService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/LevelService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/PresentationService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/SaveContentManager.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/ModuleControllerTest.java
- src/test/java/com/fluveny/fluveny_backend/business/service/ModuleServiceTest.java
at this pull request was standardized all method names
> Refactor/service method naming US-2023

- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/ExerciseEntity.java
- src/test/java/com/fluveny/fluveny_backend/business/service/ExerciseServiceTest.java
In this branch, the test class for the ExerciseService was created.
The repository class was not created because we don’t have any methods yet.
> Creating test class for ExerciseService

- src/main/java/com/fluveny/fluveny_backend/exception/GlobalExceptionHandler.java
This branch includes the implementation of exception handling for empty request bodies
> Handling empty request body exception

- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseController.java
- src/main/java/com/fluveny/fluveny_backend/business/service/GrammarRuleModuleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/GrammarRuleModuleEntity.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseControllerTest.java
In this branch, the grammar rule module now includes an embedded grammar document instead of an ID.
> Fixing Grammar Rule in Grammar Rule Module

- src/main/java/com/fluveny/fluveny_backend/business/service/GrammarRuleModuleService.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseControllerTest.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/ModuleControllerTest.java
- src/test/java/com/fluveny/fluveny_backend/business/service/GrammarRuleModuleServiceTest.java
- src/test/java/com/fluveny/fluveny_backend/business/service/ModuleServiceTest.java
- src/test/java/com/fluveny/fluveny_backend/infraestructure/repository/GrammarRuleModuleRepositoryTest.java
In this branch, unit tests were created for the Grammar Rule Module repository and service.
> Creating test classes for the Grammar Rule Module service and repository

- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
- src/main/resources/application-dev.properties
In this branch, the service method for deleting a module was created and the application properties port was fixed.
> Creating a method in the service to delete a module

- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseController.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/GrammarRulePresentationController.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/ExerciseResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/IntroductionResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/PresentationResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/TextBlockResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/ExerciseMapper.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/PresentationMapper.java
In this branch, I added the functions return as DTOs and fixed the function call for verifying the existence of the module.
> Fixing issues in the DTO and in the function call

- src/main/java/com/fluveny/fluveny_backend/api/mapper/PresentationMapper.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/GrammarRuleExerciseControllerTest.java
In this branch, the test class was modified because it was setting the wrong item in the DTO.
> Fix Grammar Rule Module Test

- pom.xml
- src/main/java/com/fluveny/fluveny_backend/RunOnStatup.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/RoleController.java
- src/main/java/com/fluveny/fluveny_backend/api/controller/UserController.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/UserRequestDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/dto/UserResponseDTO.java
- src/main/java/com/fluveny/fluveny_backend/api/mapper/UserMapper.java
- src/main/java/com/fluveny/fluveny_backend/api/response/role/RoleResponse.java
- src/main/java/com/fluveny/fluveny_backend/api/response/user/UserResponse.java
- src/main/java/com/fluveny/fluveny_backend/business/service/ModuleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/RoleService.java
- src/main/java/com/fluveny/fluveny_backend/business/service/UserService.java
- src/main/java/com/fluveny/fluveny_backend/config/security/SecurityConfiguration.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/RoleEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/TextBlockEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/entity/UserEntity.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/repository/RoleRepository.java
- src/main/java/com/fluveny/fluveny_backend/infraestructure/repository/UserRepository.java
In this branch, the User and Role entities were implemented along with their corresponding repositories, services, and endpoints. The system initialization logic for these entities was also added. Additionally, a bug affecting module deletion and all POST/PUT/DELETE methods was fixed, ensuring proper request handling.
The new endpoints introduced in this branch are:
GET /roles – retrieves all roles available on the platform.
POST /users – creates a new user with the specified data
>  Creating user and role endpoints

- src/main/java/com/fluveny/fluveny_backend/api/dto/UserRequestDTO.java
- src/test/java/com/fluveny/fluveny_backend/api/controller/UserControllerTest.java
- src/test/java/com/fluveny/fluveny_backend/business/service/UserServiceTest.java
In this branch, tests were added for UserController and UserService covering user creation.
> User tests
